project:
  type: book

book:
  title: "Combinatorics Notes"
  author: "Sera Gunn"
  date: today
  repo-url: https://github.com/seragunn/combinatorics-notes/
  site-url: https://seragunn.github.io/combinatorics-notes/
  repo-actions: [edit, issue, source]
  downloads: [pdf]
  favicon: icon.svg
  sidebar:
    background: primary
  navbar:
    background: "#222"
    left:
      - text: Home
        href: https://seragunn.github.io/
      - text: Applied Combinatorics
        href: https://www.appliedcombinatorics.org/book/app-comb.html
  chapters:
    - index.qmd
    - preface.qmd
    - part: "Trees"
      chapters:
        - trees/trees.qmd
    - part: "Strings"
      chapters:
        - strings/forbidden.qmd
        - strings/string-exercises.qmd
    - part: "Inclusion-Exclusion"
      chapters:
        - inclusion-exclusion/inclusion-exclusion.qmd
        - inclusion-exclusion/totient.qmd
    - part: "Permutations"
      chapters:
        - permutations/permutations.qmd
        - permutations/visual.qmd
        - permutations/generators.qmd
        - permutations/sign.qmd
        - permutations/inversions.qmd
        - permutations/permutation-exercises.qmd
    - part: "Generating Functions"
      chapters:
        - generating-functions/weights.qmd
        - generating-functions/ogf.qmd
        - generating-functions/multiplication.qmd
        - generating-functions/stars-and-bars-revisited.qmd
        - generating-functions/coefficient-extraction.qmd
        - generating-functions/generating-function-exercises.qmd
    - part: "Regular Languages"
      chapters:
        - regular-languages/regular-languages.qmd
        - regular-languages/finite-automata.qmd
        - regular-languages/putting-it-together.qmd
        - regular-languages/transfer-matrix.qmd
        - regular-languages/regular-languages-exercises.qmd

format:
  html:
    theme: journal
    css: style.css
    default-image-extension: svg
  pdf:
    fig-width: 2
    default-image-extension: pdf
    include-in-header:
      text: |
        \usepackage[utf8]{inputenc}
        \usepackage{mathrsfs}
        \usepackage{textalpha}

pdf-engine: pdflatex

execute:
  freeze: true
